apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: elk
  name: elasticsearch-storageclass
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
  resourceGroup: elk-aks