apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: "k8s-cluster"
    network.host: 0.0.0.0
    xpack.license.self_generated.type: basic
    xpack.security.enabled: "true"
    xpack.monitoring.collection.enabled: "true"