apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: elk
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - image: busybox
          name: increase-vm-max-map
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 0.5Gi
              cpu: "500m"
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: ES_JAVA_OPTS
              value: "-Xmx256m -Xms256m"
            - name: ELASTIC_PASSWORD
              value: changeme
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml  
              subPath: elasticsearch.yml      
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
            defaultMode: 420
