apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: es-data-svc
  labels:
    elasticsearch: elasticsearch
    role: data
spec:
  clusterIP: None
  selector:
    elasticsearch: elasticsearch
    role: data
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: node-to-node
