apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: elk
  name: es-data
  labels:
    elasticsearch: elasticsearch
    role: data
spec:
  serviceName: elasticsearch
  replicas: 2
  selector:
    matchLabels:
      elasticsearch: elasticsearch
      role: data
  template:
    metadata:
      labels:
        elasticsearch: elasticsearch
        role: data
    spec:
      initContainers:
        - image: busybox
          name: increase-vm-max-map
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: add-folder-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: es-data
          image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
          resources:
            limits:
              memory: 1Gi
              cpu: "500m"
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ES_JAVA_OPTS
              value: "-Xmx512m -Xms512m"
            - name: ELASTIC_PASSWORD
              value: changeme
            - name: "discovery.zen.minimum_master_nodes"
              value: "2"
            - name: "discovery.zen.ping_timeout"
              value: "5s"
          volumeMounts:
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml  
              subPath: elasticsearch.yml     
            - name: data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: config
          configMap:
            name: elasticsearch-data-config
            defaultMode: 420
        - name: data
          persistentVolumeClaim:
            claimName: es-data-pvc