kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data-pvc
  namespace: elk
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi