apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana-svc
spec:
  type: ClusterIP
  selector:
    kibana: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      protocol: TCP
