apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: kibana-config
  labels:
    kibana: kibana
data:
  kibana.yml: |
    server.name: kibana
    server.host: 0.0.0.0
    elasticsearch.hosts: [
    "http://elasticsearch-svc.elk.svc.cluster.local:9200" ] 
    monitoring.ui.container.elasticsearch.enabled: "true"
    elasticsearch.username: "elastic"
    elasticsearch.password: "changeme"

