apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: elk
  name: elasticsearch
  labels:
    elasticsearch: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      elasticsearch: elasticsearch
  template:
    metadata:
      labels:
        elasticsearch: elasticsearch
    spec:
      initContainers:
        - image: busybox
          name: increase-vm-max-map
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: add-folder-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
          resources:
            limits:
              memory: 1Gi
              cpu: "500m"
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          env:
            - name: ES_JAVA_OPTS
              value: "-Xmx512m -Xms512m"
            - name: ELASTIC_PASSWORD
              value: password
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml  
              subPath: elasticsearch.yml     
            - name: data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: config
          configMap:
            name: elasticsearch-config
            defaultMode: 420
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
