apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: elasticsearch-svc
spec:
  type: ClusterIP
  selector:
    elasticsearch: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: 9300
      protocol: TCP
