apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: elk
  name: elasticsearch-pvc
spec:
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce