apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: logstash-pipeline
  labels:
    logstash: logstash
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      tcp {
        port => 5000
      }
    }
    filter {
      grok {		
          match => [ "message", "%{TIMESTAMP_ISO8601:logdate} \[%{DATA:logType}\] \[%{DATA:httpVerb}\] \[%{DATA:host}\] \[%{DATA:url}\] \[%{DATA:refferrerUrl}\] \[%{DATA:queryString}\] \[%{DATA:body}\] \[%{DATA:transactionId}\] \[%{DATA:companyId}\] \[%{DATA:employeeId}\]" ]
      }
      date {
          match => ["logdate", "yyyy-MM-dd HH:mm:ss.SSS Z"]
          target => "@timestamp"
      }
    }
    output {
      elasticsearch {
        hosts => "elasticsearch-svc.elk.svc.cluster.local:9200"
        user => "elastic"
        password => "password"
        ecs_compatibility => disabled
      }
    }