apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: logstash-loadbalancer-svc
spec:
  selector:
    logstash: logstash
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    - port: 5044
      targetPort: 5044
      protocol: TCP
      name: beats